### ISSUE TITLE
* Section 12: The inner if clauses in the pseudo-code seem to be   inconsistent

### ISSUE THREAD

**Issue by gorryfair** [tsvwg/draft-ietf-tsvwg-udp-options#10]
Erik: The inner if clauses in the pseudo-code seem to be
>   inconsistent:
>
>   When (OCS == 0 and UDP CS != 0), both sub-clauses of the second outer
>   if clause are true, and thus the options need to be both ignored
>   (first sub-claused) and processed (second sub-clause).

This issue was raised in
https://mailarchive.ietf.org/arch/msg/tsvwg/ocDWz4jWZdqVP6CTuAhsBXer2Bc/

and answered (but not resolved) in
https://mailarchive.ietf.org/arch/msg/tsvwg/CnPYSXjPPmLtNkBtjJ4BSgMX2Ck/

See also
https://mailarchive.ietf.org/arch/msg/tsvwg/7nC8VbdxdcXiMjVBpnkZn7Dw6ZU/

**Comment by jtouch** [comment]
Agreed with Gorry; I checked this and updated the text to catch all the pending changes, but the pseudo-code is correct in the test above.

**Comment by auerswal** [comment]
Well, the pseudo code gives two logical expressions for correct or zero UDP checksum:

1. ((OCS != 0 and fails or OCS == 0) and UDP CS != 0) or ((OCS != 0 and passes) and UDP CS == 0)
2. OCS != 0 and passes or OCS == 0 when UDP CS != 0

The case with OCS == 0 and UDP CS != 0 (and passes) makes both expressions true. But they seem to be intended to be mutually exclusive, since they specify mutually exclusive behavior. I call this inconsistent.

The problem is "UDP CS **!=** 0" in the second expression. I'd say that this should be "==".

I think the following version with a modification of the only second expression might capture the intent:

1. ((OCS != 0 and fails or OCS == 0) and UDP CS != 0) or ((OCS != 0 and passes) and UDP CS == 0)
2. (OCS != 0 and passes) or (OCS == 0 and UDP CS == 0)

Changing "!=" to "==" is necessary. Using parentheses helps readability. Using "and" instead of "when" is more consistent.

**Comment by jtouch** [comment]
Ah - thanks, now I see what you're getting at, and yes, the second should be CS==0 and it's better to replace "when" with "and". Will do in next rev.

**Comment by jtouch** [comment]
Fixed in rev -24

**Comment by auerswal** [comment]
Indeed, that is inconsistent with section 8 which states:
```
   >> When the UDP checksum is zero, the OCS MAY be unused, and is then
   indicated by a zero OCS value.
```
The pseudo-code in section 13 **requires** OCS==0 when CS==0, while section 8 **allows** both OCS!=0 and OCS==0 when CS==0.

**Comment by jtouch** [comment]
OK - please confirm whether fixed in -25

**Comment by auerswal** [comment]
Looks good to me. :-)

**Comment by Mike-Heard** [comment]
> Looks good to me. :-)

I concur and recommend closing this issue.

**Comment by gorryfair** [comment]
Resolved

**Comment by Mike-Heard** [comment]
There is one more update in the editor's copy of -33:

OLD:
>        if the UDP checksum fails then
>            silently drop the entire UDP packet (per RFC1122)
>        if the UDP checksum passes or is zero then
>            if ((OCS != 0 and fails or OCS == 0) 
>               and UDP CS != 0) then
>                deliver the UDP user data but ignore other options 
>                (this is required to emulate legacy behavior)
>            if (OCS != 0 and passes) or 
>               (OCS == 0 and UDP CS == 0) then
>                deliver the UDP user data after parsing 
>                and processing the rest of the options, 
>                regardless of whether each is supported or succeeds
>                (again, this is required to emulate legacy behavior)


NEW:
>         if the UDP checksum fails then
>            silently drop the entire UDP packet (per RFC1122)
>        if the UDP checksum passes or is zero then
>            if (OCS != 0 and fails) or 
>               (OCS == 0 and UDP CS != 0) then
>                deliver the UDP user data but ignore other options 
>                (this is required to emulate legacy behavior)
>            if (OCS != 0 and passes) or 
>               (OCS == 0 and UDP CS == 0) then
>                deliver the UDP user data after parsing 
>                and processing the rest of the options, 
>                regardless of whether each is supported or succeeds
>                (again, this is required to emulate legacy behavior)

The new version is logically equivalent to what was in -32, but to the editor seems clearer.

**Comment by auerswal** [comment]
I also think that the new version is easier to read.
