### ISSUE TITLE
NiTs on draft-ietf-tsvwg-udp-options-28

### ISSUE THREAD

**Issue by gorryfair** [tsvwg/draft-ietf-tsvwg-udp-options#22]
Erik: The typo fix for "DPLPMTUD" actually introduced another
incorrect variant, "DLPMTUD".  This occurs three times in
draft-ietf-tsvwg-udp-options-28.txt, on the following pages:

  * page 6 (last sentence)
  * page 27 (second paragraph below figure 15)
  * page 42 (3rd paragraph of section 24)

The correct abbreviation is "DPLPMTUD":

    Datagram
    Packetization
    Layer
    Path
    Maximum
    Transmission
    Unit
    Discovery

**Comment by Mike-Heard** [comment]
Add to the nits: in Section 11.4, pp. 24-25, the numbering of the steps in creating a fragmented packet starts at 7 and ends at 11; it should start at 1 and end at 5. That can probably be fixed in the Word source by putting the cursor on the first item, bring up the context e=menu with right-click, and selecting "Restart at 1" as shown below.
![Restart-at-1](https://github.com/tsvwg/draft-ietf-tsvwg-udp-options/assets/138535554/ea60cef1-fdf2-4c67-b3f0-a98d76d91c17)

**Comment by Mike-Heard** [comment]
In the IANA considerations section, please change

>  \>> Although option nicknames are not used in-band, new UNSAFE safe
>   option names SHOULD commence with the capital letter "U" and avoid
>   either uppercase or lowercase "U" as commencing safe options.

to

>  \>> Although option nicknames are not used in-band, new UNSAFE
>   option names SHOULD commence with the capital letter "U" and avoid
>   either uppercase or lowercase "U" as commencing safe options.

I.e., s/new UNSAFE safe/new UNSAFE/.

**Comment by jtouch** [comment]
All fixed in -29.

**Comment by Mike-Heard** [comment]
All fixes look good to me.

**Comment by jtouch** [comment]
fixed in pending -32 and updated to 2024 date.
