### ISSUE TITLE
Med: WGLC Comments on Magic Number?

### ISSUE THREAD

**Issue by gorryfair** [tsvwg/draft-ietf-tsvwg-udp-options#32]
* I think putting a magic number (hex of the RFC number to be assigned to the doc) right before the OCS will explicitly indicates that the surplus area is encoded per the current spec. Otherwise, how to determine that the first two bytes are actually for OCS.

(Added by GF during WGLC)

**Comment by Mike-Heard** [comment]
Given the lack of evidence for any existing non-standard uses of the surplus area, I am not convinced that this is necessary, but I would not object if it would once and for all put to that issue to bed (see Tom Herbert's review https://mailarchive.ietf.org/arch/msg/tsvwg/qbc3I4qHDHj43vBrJWJFKoI-Byk/, where this was once again raised).

**Comment by gorryfair** [comment]
I also am not aware if any existing specifications using this area. I am assuming that from the perspective of UDP Options, the OCS provides the required function, so is another magic number needed?

**Comment by boucadair** [comment]
The risk is actually not with existing but:

>    OCS is not intended to prevent future non-standard uses of the
>    surplus area, nor does it enable shared use with mechanisms that do
>    not comply with UDP options.

I still think we need some explicit indicator.

**Comment by gorryfair** [comment]
The kind field is providing the extension point. Couldn't future extensibility be allowed by defining a new UDP Option? 
Another field would seem to add overhead, but I'm not yet sure that I understand problem needs this in future.

**Comment by Mike-Heard** [comment]
> Couldn't future extensibility be allowed by defining a new UDP Option? 

Indeed it could. A new option that is placed after OCS (possibly with a NOP for alignment) that consumes the remainder of the surplus area will accomplish this objective. If that option does not affect the interpretation of the preceding UDP data area if it is ignored, it can be assigned a SAFE option codepoint; in that case an extended length field might be needed . If the option can't be safely ignored, then then it would need to be assigned an UNSAFE codepoint. In that case, it could be **defined** to consume the remainder of the surplus area (much like FRAG) and thereby not need an extended length field.

**Comment by gorryfair** [comment]
Looking at this thread, I suggest we close it by adding a description above to explicitly show one way this can be extended. I concur, this does not require a specific magic number.

**Comment by boucadair** [comment]
Looks like a good plan. Thanks.

**Comment by jtouch** [comment]
I thought this was already addressed; as before, IMO this can be an ExID if someone cares, but shouldn’t be baked into the protocol because we have no example of conflicting use that warrants it.  Note that new options (not defined in the base spec) cannot define constraints outside their length field; if they do, they would not be interpreted correctly by non-updated option-aware endpoints. I think this whole issue should be dropped.

**Comment by Mike-Heard** [comment]
Question for Med and Gorry:

I see the following bolded text in Section 9 stating that future extensibility is possible by defining a new UDP Option:

>>\>\> Only the OCS, AUTH, and UENC options include fields within the
   options that depend on the contents of the surplus area. AUTH and
   UENC are never used together, as UENC would serve both purposes.
   AUTH and UENC are always computed as if their hash and the OCS are
   zero; the OCS is always computed as if its contents are zero and
   after the AUTH or UENC hash has been computed. Future options MUST
   NOT be defined as having an option field value dependent on the
   remaining contents of the surplus area, i.e., the area after the
   last option (presumably EOL). Otherwise, interactions between those
   values, the OCS, and the AUTH and UENC options could be
   unpredictable. **This does not prohibit future uses of the entire
   surplus area; space that would have occurred after the EOL can be
   used as a UDP option instead, i.e., rather than using the EOL option
   and trying to defining meaning beyond it, define a new option that
   uses the remaining surplus area as an option itself, in conjunction
   with an assigned UDP option codepoint and length to unambiguously
   indicate the meaning of that area.** This also does not prohibit
   options that modify later options (in order of appearance within a
   packet), such as would typically be the case for compression (UCMP).

Based on this, I am inclined to say that we don't need any new text. If you disagree, suggestions on what to say and where to put it would be helpful to the editor.

**Comment by boucadair** [comment]
Thanks for checking this Mike. We can consider this closed.
