### ISSUE TITLE
Tom H: WGLC Additions to terminology in Section 3

### ISSUE THREAD

**Issue by gorryfair** [tsvwg/draft-ietf-tsvwg-udp-options#35]
Definition of User-- in most other protocols User means users as in
people. I think Application would be a better term for this document

SAFE and UNSAFE options should be defined in this section

(Added by GF during WGLC)

**Comment by Mike-Heard** [comment]
I concur with the addition of crisp definitions of SAFE and UNSAFE in this section, and I propose the following definitions:

A SAFE option is one that does not change the UDP user data or how it is interpreted and thus can be safely ignored by a receiver that does not understand it.

An UNSAFE option is one that does change the UDP user data or how it is interpreted and thus cannot be safely ignored by a receiver that does not understand it.

See also Issue #40 and Issue #23 (closed).

**Comment by gorryfair** [comment]
I'd expect a definition of user could be added to the terminology. For me (as an individual), the "User" in the User Datagram Protocol (UDP) is the application or upper-layer protocol that operates over UDP.

**Comment by jtouch** [comment]
The proposed text is far too subjective, especially because every option arguably changes the meaning of the user data and the interpretation of what can be ignored is in the eye of the beholder.

I propose sticking to the objective only and highlighting the onus on the option designer, not simply the choice of the receiver:

A SAFE option is one that does not alter the UDP user data as received from the application layer and thus needs to be designed to be safely ignored by a receiver that does not understand it.

An UNSAFE option is one that does alter the UDP user data or how it is interpreted andand thus does not need to be designed to be safely ignored by a receiver that does not understand it.

**Comment by Mike-Heard** [comment]
Proposed definitions currently in Section 3 of the editor's copy of -33:

o	SAFE options – UDP options that are designed to be safe for a receiver that does not understand them to ignore. Such options MUST NOT alter the UDP user data or how it is intended to be interpreted by the user/application layer.

o	UNSAFE options – UDP options that are not designed to be safe for a receiver that does not understand them to ignore. Such options MAY alter the UDP user data or how it is intended to be interpreted by the user/application layer, but there are restrictions on how they can be transmitted, as noted in Sections 10 and 12.
 
Hopefully this satisfies the request to put the onus on the designer. Note that the words "how it is interpreted" have been changed to "how it is intended to be interpreted" and put into both definitions. Again the intent is to emphasize the intent of the designer.

**Comment by jtouch** [comment]
I disagree with the "how it is interpreted" part; interpretation is always a uniquely receiver perspective. I.e., if I send ASCII and you interpret it as EBCDIC, that's on you. It's only when the actual information being sent is different than what we would have sent to a legacy receiver that we end up with a problem

Besides, "how it is interpreted" or "intended to be interpreted" is far to vague; I don't think it should be ambiguous as to whether an option is SAFE or UNSAFE. Receiver interpretation (or sender intent of the interpretation) isn't what makes an option safe; it's safe when a legacy receiver would have gotten and can use the same information the same way.

**Comment by Mike-Heard** [comment]
Allow me to point out that you wrote "how it is interpreted" in your suggested text above:

> An UNSAFE option is one that does alter the UDP user data or **how it is interpreted**

which inspired me to adopt that wording into the proposed definitions. I am sorry that the result was not satisfactory.

I do think that we have an important problem to solve. You may recall that we had a proposal (draft-daiya-tsvwg-udp-options-next-header) to use a UDP "next header" option instead of the port number to identify the upper layer protocol. That would cause problems for a legacy receiver because it is blind to UDP options and would be unable to dispatch received packets to the correct upper layer module -- even though the user data in the packets is unaltered. On that basis, I think that it was a technical error for draft-daiya to request an option number from the SAFE range. It should have been requested from the UNSAFE range instead.

It seems to me that it behooves us to frame the distinction between SAFE and UNSAFE in such a way that that option designers do not repeat the error made in draft-daiya. To me, identifying the upper layer protocol in a transmitted packet amounts to a specification of how the data is the packet is "intended to be interpreted."  But if those words are too vague, I am by no means wedded to them. Let's see if we can find a satisfactory wording that solves problem. Do you have any suggestions?

**Comment by jtouch** [comment]
My comment from 3 days ago has a paste error on the UNSAFE definition. It should have been:

>>An UNSAFE option is one that does alter the UDP user data and thus does not need to be designed to be safely ignored by a receiver that does not understand it.<<

The issue is the original phrase "or how it is interpreted" and the new "or how it is intended to be interpreted". I agree that a mark that indicates "these are EBCDIC bytes" would be UNSAFE (because a legacy receiver would interpret them as just bytes with no meaning), in the same way as the upper layer protocol indicator mentioned.

Maybe the issue to me is that this ought to be defined from the sender's viewpoint, e.g., "or to signal a change in what its contents represent". I.e., saying "this is EBCDIC" is just as bad as actually converting the bytes to EBCDIC.

(my concern is that "interpretation" is vague and "intended" isn't quite the same as actually signaled).

**Comment by Mike-Heard** [comment]
That is an excellent suggestion. I will change the phrase " how it is intended to be interpreted by the user/application layer" to ""or to signal a change in what its contents represent". I'll update this issue with resulting text of the definitions when I have it crafted.

**Comment by Mike-Heard** [comment]
That is an excellent suggestion. I have changed the phrase "or how it is intended to be interpreted by the user/application layer" to "or signal a change in what its contents represent". Here are the updated definitions:

o	SAFE options – UDP options that are designed to be safe for a receiver that does not understand them to ignore. Such options may not alter the UDP user data or signal a change in what its contents represent.

o	UNSAFE options – UDP options that are not designed to be safe for a receiver that does not understand them to ignore. Such options may alter the UDP user data or signal a change in what its contents represent, but there are restrictions on how they can be transmitted; these restrictions are noted in Sections 10 and 12.
